"""CandidateSignal and ApprovedSignal ORM models."""

from datetime import datetime
from decimal import Decimal
from typing import Optional
from uuid import UUID

from sqlalchemy import Boolean, ForeignKey, Index, Numeric, String, text
from sqlalchemy.dialects.postgresql import JSONB, UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from src.database import Base


class CandidateSignalORM(Base):
    """Raw signal generated by a strategy before pipeline processing."""

    __tablename__ = "candidate_signals"
    __table_args__ = (
        Index("idx_candidate_created", "created_at"),
        Index("idx_candidate_status", "status"),
    )

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    strategy: Mapped[str] = mapped_column(String(30), nullable=False)
    direction: Mapped[str] = mapped_column(String(5), nullable=False)
    entry_price: Mapped[Decimal] = mapped_column(Numeric(12, 5), nullable=False)
    sl_price: Mapped[Decimal] = mapped_column(Numeric(12, 5), nullable=False)
    tp1_price: Mapped[Decimal] = mapped_column(Numeric(12, 5), nullable=False)
    tp2_price: Mapped[Optional[Decimal]] = mapped_column(Numeric(12, 5), nullable=True)
    confidence: Mapped[Decimal] = mapped_column(Numeric(4, 3), nullable=False)
    timeframe: Mapped[str] = mapped_column(String(5), nullable=False)
    params_snapshot: Mapped[dict] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[datetime] = mapped_column(nullable=False, server_default="NOW()")
    status: Mapped[str] = mapped_column(String(15), nullable=False, default="PENDING")


class ApprovedSignalORM(Base):
    """Signal approved after full pipeline processing."""

    __tablename__ = "approved_signals"

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    candidate_signal_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("candidate_signals.id"),
        nullable=False,
    )
    rank_score: Mapped[Decimal] = mapped_column(Numeric(6, 4), nullable=False)
    risk_check_passed: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    execution_status: Mapped[str] = mapped_column(String(15), nullable=False, default="PENDING")
    created_at: Mapped[datetime] = mapped_column(nullable=False, server_default="NOW()")
